### ISSUE TITLE
🤖 ADD GIT TEMPLATE 💪😎🤳

### ISSUE THREAD

**Issue by corners2wall** [corners2wall/Skyscraper#1]
Hello everyone! This project needs git templates for convenient create git entities.  🧐
So task: 🙋
Add beautiful git template in root directory ./github
types of template:
- ISSUE_TEMPLATE.md, 🤯
- PULL_REQUEST_TEMPLATE.md 🤯
and others if you want it.

Good luck and have fun! 🧡

**Comment by Saurabhyadav0** [comment]
Sir please guide me how to do this project..

**Comment by laxitajain** [comment]
hi, can you please assign this to me?

**Comment by corners2wall** [comment]
@laxitajain  you will do this?

**Comment by laxitajain** [comment]
yeah! i would love to!

**Comment by corners2wall** [comment]
@laxitajain  assign to you

**Comment by Saurabhyadav0** [comment]
> @laxitajain you will do this?

sir , i want to do but

**Comment by corners2wall** [comment]
@laxitajain  you can try too. If your solution will be better. I merge your pull request.

**Comment by Saurabhyadav0** [comment]
thank you sir

**Comment by corners2wall** [comment]
@Saurabhyadav0 please don't spam in others issues

**Comment by Pooja1672** [comment]
Hi  @corners2wall , Can you assign this issue to me...I would like to work on it

**Comment by corners2wall** [comment]
@Pooja1672, already. please do amazing stuff 📈💯⭐

**Comment by Pooja1672** [comment]
Hi @corners2wall , can you please check I made a PR for the templates.

**Comment by corners2wall** [comment]
Closes in #18
