### ISSUE TITLE
🤖 Add Airbnb style guide 💪😎🤳

### ISSUE THREAD

**Issue by corners2wall** [corners2wall/Skyscraper#12]
Hello everyone! This repo needs good code style checking for better contribute into a project. 📈
So task: 🙋
- add style guide airbnb into eslint;

Useful links: 
[eslint-config-airbnb-typescript](https://www.npmjs.com/package/eslint-config-airbnb-typescript)

JUST DO IT 💪💪💪
Good luck and have fun! 🧡

**Comment by Dhoni77** [comment]
Hi @corners2wall I would like to work on this

**Comment by corners2wall** [comment]
@Dhoni77  No problem, go go go

**Comment by HuynhQuanB2014943** [comment]
Hi, you can assigned for me ?

**Comment by corners2wall** [comment]
@HuynhQuanB2014943  go bro

**Comment by Dhoni77** [comment]
Hi @corners2wall  The eslint config has been added by you?

**Comment by corners2wall** [comment]
@Dhoni77  yeap)

**Comment by Dhoni77** [comment]
Then this issue can be closed right?

**Comment by corners2wall** [comment]
Yes, thank you for wanting to help
You can do any other work in this project if you want. 
Just create a pr with the changes
