### ISSUE TITLE
🤖 ADD GIT PIPELINE 💪😎🤳 

### ISSUE THREAD

**Issue by corners2wall** [corners2wall/Skyscraper#2]
Hello everyone! This project needs git pipeline for better build process . 🧐
So task: 🙋
Add pipeline for this project. 

I don't need to add a detailed description since you already know what to do. 🔥🔥🔥

### JUST DO IT 💪💪💪

Good luck and have fun! 🧡

**Comment by Saurabhyadav0** [comment]
Hello sir , i am new to this platform  kindly guide me i don't have any idea about  how to add pipeline in this project please guide me

**Comment by Saurabhyadav0** [comment]
and assign me this project

**Comment by Saurabhyadav0** [comment]
Sir @corners2wall can you assign me this project.

**Comment by Rachit1313** [comment]
Could you please brief what kind of pipeline do you want? for what process

**Comment by corners2wall** [comment]
@Rachit1313  We need checking the lint, testing maybe something else. But the project doesn't have this scripts. Could you add stub and when this functionality will add in future we can add into the pipeline.

**Comment by Rachit1313** [comment]
sure I will create a workflow for checking lint once #4  is completed. Can you assign this to me?

**Comment by corners2wall** [comment]
no problem

**Comment by Rachit1313** [comment]
Hi,
Sorry for the delay on this one.
I wrote the workflow for this one but when I ran lint on your current code I found these errors:
![image](https://github.com/corners2wall/Skyscraper/assets/58596563/d6e7bace-6e61-4907-a0f5-c9bde9fcf470)

**Comment by corners2wall** [comment]
@Rachit1313  I will fixed this in future. Thanks
