### ISSUE TITLE
🤖 UPDATE README.MD💪😎🤳 

### ISSUE THREAD

**Issue by corners2wall** [corners2wall/Skyscraper#3]
Hello everyone! This repo needs good `readme.md` for better understanding a project. 🧐
So task: 🙋
Add next section in `readme.md`;
- What is inside? (core dependencies in your  view in package.json file);
- Game example (add game process gif);
- Contributors (how contribute in this project, maybe add bot or other solution);
and others if you want it.

I don't need to add a detailed description since you already know what to do. 🔥🔥🔥

JUST DO IT 💪💪💪
Good luck and have fun! 🧡

**Comment by Saurabhyadav0** [comment]
hello sir please tell me what to do in this project  i read the description but could not understand what to do and how to do?

**Comment by Saurabhyadav0** [comment]
Sir @corners2wall can you assigned me this project.

**Comment by Alstudd** [comment]
Assign this to me. I will work on this issue

**Comment by corners2wall** [comment]
Okey, men. Make this one cool :sunglasses:

**Comment by Alstudd** [comment]
@corners2wall I have made my PR. You can review it!

**Comment by corners2wall** [comment]
@Alstudd This is wonderful work. Thank you

**Comment by Alstudd** [comment]
Dude, can u add hacktoberfest-accepted label to my pr so that it can be accepted for hacktoberfest or will it still work?

**Comment by corners2wall** [comment]
No problem bro
