### ISSUE TITLE
🤖 ADD PRETTIER AND LINTER💪😎🤳

### ISSUE THREAD

**Issue by corners2wall** [corners2wall/Skyscraper#4]
Hello everyone! This repo needs good code style checking for better contribute into a project. 📈
So task: 🙋
- Add prettier; 🔧
- Add esLint; 🔨
- Add script for linting in `package.json`; 
- Some packages for linting typescript; 

In pull request description write about added packages. 📝📝📝

I don't need to add a detailed description since you already know what to do. 🔥🔥🔥

JUST DO IT 💪💪💪
Good luck and have fun! 🧡

**Comment by ad-astra-per-ardua** [comment]
Hi, Can i try this? @corners2wall

**Comment by Rachit1313** [comment]
I would like to work on this

**Comment by corners2wall** [comment]
@d982h8st7 , @Rachit1313  
### JUST DO IT,  GUYS
![just-do-it-do-it](https://github.com/corners2wall/Skyscraper/assets/110557519/3eb41547-b953-410d-abfc-40421599e24b)

**Comment by ad-astra-per-ardua** [comment]
@Rachit1313 Can i do Prettier?

**Comment by Rachit1313** [comment]
> @Rachit1313 Can i do Prettier?

Sorry, I just completed the prettier one. Is it possible for you to complete the esLint ?

**Comment by ad-astra-per-ardua** [comment]
> > @Rachit1313 Can i do Prettier?
> 
> Sorry, I just completed the prettier one. Is it possible for you to complete the esLint ?

no problem

**Comment by Rachit1313** [comment]
Hey @corners2wall , I just created a PR for prettier but it shows me deployment checks failed. Were the checks passing previously because I didn't change anything in the code except adding prettier config file and the package itself.

**Comment by Rachit1313** [comment]
> Hey @corners2wall , I just created a PR for prettier but it shows me deployment checks failed. Were the checks passing previously because I didn't change anything in the code except adding prettier config file and the package itself?

or if @d982h8st7 you can check the PR and help me with this part?

**Comment by Rachit1313** [comment]
Hey @corners2wall , I just updated the PR #5 . All the checks have been passed. Could you please review it ?

**Comment by corners2wall** [comment]
@Rachit1313  build failure. This happened because you didn't add the package in yarn :(
Use `yarn install` command

**Comment by Rachit1313** [comment]
> @Rachit1313 build failure. This happened because you didn't add the package in yarn :( Use `yarn install` command

yup just fixed it, Sorry for inconvience.

**Comment by Rachit1313** [comment]
@d982h8st7 , Could you please confirm if you're working on adding esLint or shall I do?

**Comment by ad-astra-per-ardua** [comment]
> @d982h8st7 , Could you please confirm if you're working on adding esLint or shall I do?

Yup, im currently working on it

**Comment by corners2wall** [comment]
Thanks guys. Well done
