### ISSUE TITLE
🤖 2 MINUTES FIX!!! DON'T PASS BY 💪😎🤳

### ISSUE THREAD

**Issue by corners2wall** [corners2wall/Skyscraper#6]
Hello everyone! This repo has bug 😕 
We should fix this. Any way... 
So bug: :bug: 
In browser page looks next: 
![image](https://github.com/corners2wall/Skyscraper/assets/110557519/6cfe49d7-1def-4cf1-88e0-90f8f803351b)
- Please change the page title to "Skyscraper".
- Add favicon. Looks like build ->  :building_construction:  or 🏢

JUST DO IT 💪💪💪
Good luck and have fun! 🧡

**Comment by LalitDeore** [comment]
Could you please assign this task to me?

**Comment by corners2wall** [comment]
@LalitDeore  no problem

**Comment by corners2wall** [comment]
Closes in #11
